# Generated by Django 3.2.9 on 2022-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humid', models.IntegerField()),
                ('dust', models.IntegerField()),
                ('superdust', models.IntegerField()),
                ('tvoc', models.FloatField()),
            ],
        ),
    ]
