# Generated by Django 3.2.9 on 2022-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.IntegerField()),
                ('middle', models.IntegerField()),
                ('short', models.IntegerField()),
            ],
        ),
    ]
